"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const dotenv_1 = __importDefault(require("dotenv"));
const db_1 = __importDefault(require("./config/db"));
const userRoutes_1 = __importDefault(require("./routes/userRoutes"));
const eventsRouter_1 = __importDefault(require("./routes/eventsRouter"));
const adminRoutes_1 = __importDefault(require("./routes/adminRoutes"));
const UserController_1 = require("./controllers/UserController");
dotenv_1.default.config();
(0, db_1.default)();
const app = (0, express_1.default)();
const PORT = process.env.PORT;
app.use(express_1.default.json());
app.use('/api/users', userRoutes_1.default);
app.use('/api/', eventsRouter_1.default);
app.use('/api/admin', adminRoutes_1.default);
(0, UserController_1.createPermanentAdminUser)();
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
